### ISSUE TITLE
extension did not record transaction SQL like "begin","rollback","commit"

### ISSUE THREAD

**Issue by toxmc** [tideways/php-xhprof-extension#60]
tideways => 4.1.6
extension did not record transaction SQL like "begin","rollback","commit"

PDO function list:
![image](https://user-images.githubusercontent.com/3990846/44518184-31aa1680-a6fc-11e8-948e-810822fc8e85.png)

SQL list:
![image](https://user-images.githubusercontent.com/3990846/44518550-1be92100-a6fd-11e8-97b0-764af861efea.png)

**Comment by beberlei** [comment]
Hi @toxmc 

You are right, but we will not change this anymore. The PHP extension 4.1.6 is in maintenance mode, we have since released a version 5.0 for the SQL and Timeline profiling that is not open-source and only works with our tideways.com product.

You can still get the original XHProf callgraph profiling code here from the `master` branch of this repository.
