### ISSUE TITLE
Download feed for SaaS extension

### ISSUE THREAD

**Issue by Zanadar** [tideways/php-xhprof-extension#88]
Hey!
I'm one of the maintainers of the https://github.com/cloudfoundry/php-buildpack 
We currently build php with support for `tideways_xhprof ` in multiple versions (one pinned at 4.1.7 another tracking the latest releases). Is there a feed somewhere where we can consume released versions of the `tideways` extension so that we can keep up to date with releases there instead of pinning back?

Thanks!

**Comment by beberlei** [comment]
@Zanadar can you point me to some code where tideways is installed? I couldn't find it in the repo.

We renamed the open-source extension from `tideways` to `tideways_xhprof`, because it clashed with the `tideways` extension that we use for our SaaS.

You can directly download the latest versions of the `tideways` extension and the tideways-daemon from:

- https://tideways.com/profiler/downloads/linux/daemon/latest.tar.gz
- https://tideways.com/profiler/downloads/linux/extension/latest.tar.gz

I would recommend using the packages for Debian, Ubuntu, RedHat, CentOS though that you can find here: https://tideways.com/profiler/downloads

**Comment by Zanadar** [comment]
https://github.com/cloudfoundry/binary-builder/blob/master/recipe/php_common_recipes.rb is the code we execute when do our builds of php. 

From the looks of it those extension links are for pre-compiled binaries, which I guess we'd need to do some license checking if we can redistribute? 

Generally we compile php extensions from source when we do our overall build of php. We keep our config for extension versions here: https://github.com/cloudfoundry/buildpacks-ci/blob/11e76d1abc2f1a10730f016fd156ad26c057811c/tasks/build-binary-new/php7-base-extensions.yml

For our purposes, it would be nice to see versions of the SaaS extension published in a similar fashion to github releases so that we can consume them as part of our dependency automation or at least have some sort of archive where new versions are listed so we don't have to poll that `latest` url to know if a new version is available? Not a big deal either way, just a nice-to-have.

**Comment by beberlei** [comment]
@Zanadar I looked up the recipe and the commit that added it. It looks they wanted to use the open source part of the code, so i would reocmmend to stay with this repository here and go for the recent version 5.0.1 instead of 4.1.7. It should "just work" with the Pecl Recipe, but I haven't tested it.

**Comment by Zanadar** [comment]
Sounds good. Thanks for the direction. If we decide to package both OSS
code and your proprietary extension in some way (if that's even
doable/legally possible) I'll check back in.
